
### List
GET http://localhost:3001/api/v1/pokemons
Content-Type: application/json

### Get
GET http://localhost:3001/api/v1/pokemons/2
Content-Type: application/json

### CREATE
POST http://localhost:3001/api/v1/pokemons
Content-Type: application/json

# {
#   "tipo": "Charizard",
#   "treinador": "Zoraia"
# }

{
  "tipo": "Pikachu",
  "treinador": "Ash Ketchum"
}

# {
#   "tipo": "Bulbasaur",
#   "treinador": "Jon Snow"
# }

### update
PUT http://localhost:3001/api/v1/pokemons/10
Content-Type: application/json

{
  "treinador": "Soraia"
}

### DELETE
DELETE http://localhost:3001/api/v1/pokemons/15
Content-Type: application/json


### BATTLE
POST http://localhost:3001/api/v1/battle/1/2
Content-Type: application/json